pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "madalinatoader/monitorizare-image"
        DOCKER_VOLUME = "/docker/monitoring/data:/data"
        DOCKERFILE_PATH = "jenkins/pipelines/monitoring/Dockerfile"
        SCRIPT_PATH = "/app/monitoring.sh"
    }

    stages {
        stage('Checkout SCM') {
            steps {
                echo 'Clonam repository-ul...'
                checkout scm
            }
        }

        stage('Lint Bash Script') {
            steps {
                echo 'Verificam scriptul de monitorizare...'
                script {
                    if (sh(script: 'command -v shellcheck', returnStatus: true) == 0) {
                        sh "shellcheck scripts/monitoring.sh"
                    } else {
                        echo "ShellCheck nu este instalat, se omite verificarea."
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Construim imaginea Docker...'
                sh "docker build -t ${DOCKER_IMAGE} -f ${DOCKERFILE_PATH} ."
            }
        }

        stage('Docker Login & Push') {
            steps {
                echo 'Autentificare in Docker Hub si push...'
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh "echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin"
                    sh "docker push ${DOCKER_IMAGE}"
                }
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploy local (sau pe server remote)...'
                sh """
                    mkdir -p /docker/monitoring/data
                    docker run --rm -v ${DOCKER_VOLUME} ${DOCKER_IMAGE} /bin/sh ${SCRIPT_PATH}
                """
            }
        }
    }

    post {
        always {
            echo 'Pipeline terminat!'
        }
        success {
            echo 'Pipeline finalizat cu succes!'
        }
        failure {
            echo 'Pipeline esuat!'
        }
    }
}

