// Jenkinsfile pentru pipeline-ul de backup

pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = 'docker-hub-creds'  // ID-ul credentialelor create în Jenkins
        IMAGE_NAME = 'toadermadalina/backup-image'   // imaginea Docker în Docker Hub
    }

    stages {
        stage('Checkout') {
            steps {
                // Clonare cod din Git
                git branch: 'main', url: 'https://github.com/ToaderMadalina/platforma-monitorizare.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME jenkins/pipelines/backup'
            }
        }

        stage('Docker Login') {
            steps {
                // Folosește credentialele stocate în Jenkins
                withCredentials([usernamePassword(credentialsId: "$DOCKERHUB_CREDENTIALS", 
                                                  usernameVariable: 'USERNAME', 
                                                  passwordVariable: 'PASSWORD')]) {
                    sh 'echo $PASSWORD | docker login -u $USERNAME --password-stdin'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh 'docker push $IMAGE_NAME'
            }
        }

        stage('Deploy') {
            steps {
                // Exemplu de rulare a containerului pe VM remote (poți adapta)
                sh '''
                ssh -o StrictHostKeyChecking=no ansible@192.168.1.12 "
                docker pull $IMAGE_NAME &&
                docker stop backup-container || true &&
                docker rm backup-container || true &&
                docker run -d --name backup-container -v /docker/backup/data:/backup $IMAGE_NAME
                "
                '''
            }
        }
    }

    post {
        success {
            echo 'Pipeline finalizat cu succes!'
        }
        failure {
            echo 'Pipeline eșuat!'
        }
    }
}

